language: python
python:
- 3.6
- 3.5

install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: jeandet
  password:
    secure: EWk3Twexdojw00qUmBW6shKF8ZVz+sU17JWJXA5QxX2hA4Vvq//d4m/iGhT+gJuxHYwWWSU+uk1nmaHuI7XMZASyO6vXIbSTf87UPMCi4pRu4p9X0FqCB0pWSMDBbrT1dMPwqMkuy4e24WG6u2UF5cAMAmreotTfc0pK0nbF7YqMaz4/tg1+Kgb0HDeBvCIm4inueTh7obsW4//HzqI9D7QlrcXP+SmiAKr2QdAhnnNGD3DNiMJJRfPpIxKGOqPl5giwZfMbAeRQA4cj1Rbdqg2aJu7t8MJlpFCmcVCs3waEuYDNyXU2pJSMEFB34CfHcP5Djina59sum+fI9bpQLYskG/M1ATA0Vu7VhUPmA4QMsL0LMLynLvqBAS7epTjaOaFnkc+NvoYp+5RBczCHhutAqEopgyyZTYg7XTTst+KqFKunGBZt2VkWSR6zE9PjehzmBhFzZzi9+LatVSvXm+WM6Z0denl4n6NZzPnmIClK7CK2k0c6knX6wV08CkF16+AmKjb3F9TZrGj4FeshLnnSF5r2J+kvuPggocObLkQFbArNLI3uYdkCjAK/i8WTN7pD1S/3cC+NBKnskoZ1d3nzLn/9uq9QgTgi5nBrnIzFMpXayTr3JkDkAwYUmwU7fG1GZT0CdsjABr2ZK57WnIf+IbBnOG3+wVE6uJufO3Q=
  on:
    tags: true
    repo: LaboratoryOfPlasmaPhysics/Whampyr
    python: 3.6
